FROM node:20-slim

WORKDIR /app

COPY package*.json ./

RUN rm -f package-lock.json && \
    npm install --legacy-peer-deps && \
    npm install react-is --legacy-peer-deps

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]